- README.md
- appveyor.yml
- azure-pipelines.yml
- magpylib/appveyor.yml
- tox.ini
CircleCI now uploads codecov report with tox.
Azure Pipelines tests Windows environments
Appveyor checks Python environments - possibly builds later.
> Add Windows and Python Environment CI, code coverage reporter

- README.md
- appveyor.yml
- azure-pipelines.yml
- magpylib/__init__.py
- magpylib/_lib/__init__.py
- magpylib/_lib/classes/__init__.py
- magpylib/_lib/classes/base.py
- magpylib/_lib/classes/collection.py
- magpylib/_lib/classes/currents.py
- magpylib/_lib/classes/fieldsampler.py
- magpylib/_lib/classes/magnets.py
- magpylib/_lib/classes/moments.py
- magpylib/_lib/fields/Current_CircularLoop.py
- magpylib/_lib/fields/Current_Line.py
- magpylib/_lib/fields/Moment_Dipole.py
- magpylib/_lib/fields/PM_Box.py
- magpylib/_lib/fields/PM_Cylinder.py
- magpylib/_lib/fields/PM_Sphere.py
- magpylib/_lib/fields/__init__.py
- magpylib/_lib/mathLibPrivate.py
- magpylib/_lib/mathLibPublic.py
- magpylib/_lib/utility.py
- magpylib/math/__init__.py
- magpylib/source/__init__.py
- magpylib/source/current/__init__.py
- magpylib/source/magnet/__init__.py
- magpylib/source/moment/__init__.py
- setup.py
Fix the minimum viable python version for the library in license / descriptions.
> Minimum Python Version fix

- README.md
- appveyor.yml
- azure-pipelines.yml
- docs/requirements.txt
- magpylib/__init__.py
- magpylib/_lib/__init__.py
- magpylib/_lib/classes/__init__.py
- magpylib/_lib/classes/base.py
- magpylib/_lib/classes/collection.py
- magpylib/_lib/classes/currents.py
- magpylib/_lib/classes/fieldsampler.py
- magpylib/_lib/classes/magnets.py
- magpylib/_lib/classes/moments.py
- magpylib/_lib/fields/Current_CircularLoop.py
- magpylib/_lib/fields/Current_Line.py
- magpylib/_lib/fields/Moment_Dipole.py
- magpylib/_lib/fields/PM_Box.py
- magpylib/_lib/fields/PM_Cylinder.py
- magpylib/_lib/fields/PM_Sphere.py
- magpylib/_lib/fields/__init__.py
- magpylib/_lib/mathLibPrivate.py
- magpylib/_lib/mathLibPublic.py
- magpylib/_lib/utility.py
- magpylib/math/__init__.py
- magpylib/source/__init__.py
- magpylib/source/current/__init__.py
- magpylib/source/magnet/__init__.py
- magpylib/source/moment/__init__.py
- setup.py
Lock the dependency versions and remove Python 3.5 support.
Also adjust the license so it doesn't have a minor Python version in it.
> Lock dependency versions

- README.md
- setup.py
> Add configuration for PyPi

- magpylib/_lib/classes/collection.py
- tests/test_Collection.py
#151 
Last PR was missing the array wrapper for Collection's getBsweep. This corrects this.
> Fix get bsweep array collection

- magpylib/_lib/classes/collection.py
> Add externalFig+subplotArg kwargs to displaySystem

- docs/_pages/0_documentation.md
- docs/_pages/2_guideExamples.md
This adds the guard notice to the multiprocessing section in Examples.
This also adds a keynote on the Library Documentation about the Examples guide.
> Add multiprocessing guard, multiprocessing notice

- tests/test_tarcisBug.py
#132 
#160 
Added test for Tarcis' rotation bug.
Remove this test once bug is cleared.
> Add test file for cases pertaining bug #132

- setup.py
This bumps the version to 1.1.1 for bug fixes.
> bump to 1.1.1-beta

- docs/_pages/0_documentation.md
- docs/_pages/2_guideExamples.md
There were some Sphinx warnings while building the documentation, this PR addresses them.
> Fix doc warnings

- CHANGELOG.md
- MANIFEST.in
This adds the CHANGELOG.md file which includes most notable changes for each version.
MANIFEST.ini is also modified to include both the CHANGELOG and the tests to the distribution file.
> Add changelog

- magpylib/_lib/classes/collection.py
The docstring for the Collection subplotAx kwarg was out of date.
Example code is functional.
> Update docstring for subplotAx kwarg

- CHANGELOG.md
> Changelog 1.1.1 Beta

- docs/_pages/2_guideExamples.md
- docs/_pages/3_MATLAB.md
- docs/_pages/4_contguide.md
- docs/pyplots/examples/01_SimpleCollection.py
This removes the [WIP] from some of the remaining guides.
> small doku fixes

- magpylib/_lib/classes/base.py
- magpylib/_lib/classes/collection.py
- magpylib/_lib/classes/currents.py
- magpylib/_lib/classes/magnets.py
- magpylib/_lib/classes/moments.py
- magpylib/_lib/fields/Moment_Dipole.py
- magpylib/_lib/mathLibPublic.py
#190 
Fixed all alerts, deleted unused imports and variables
> Import fixes, unused imports and variables deleted

- magpylib/_lib/fields/Current_CircularLoop.py
- magpylib/_lib/fields/Moment_Dipole.py
- magpylib/_lib/fields/PM_Box.py
- magpylib/_lib/fields/PM_Cylinder.py
- magpylib/_lib/fields/PM_Sphere.py
- tests/test_fields/test_CurrentLine.py
- tests/test_fields/test_CurrentLoop.py
- tests/test_fields/test_MomentDipole.py
- tests/test_fields/test_PMBox.py
- tests/test_fields/test_PMCylinder.py
- tests/test_fields/test_PMSphere.py
#168 
#191 
Replaced all prints in the fields through warnings, wrote tests for all of them
> Replaced the prints through warnings

- docs/_pages/2_guideExamples.md
- docs/_pages/3_MATLAB.md
- docs/_pages/4_contguide.md
- docs/pyplots/examples/01_SimpleCollection.py
- magpylib/__init__.py
- magpylib/_lib/classes/collection.py
- magpylib/_lib/classes/fieldsampler.py
- magpylib/_lib/classes/sensor.py
- magpylib/_lib/utility.py
- tests/test_Collection.py
- tests/test_sensor.py
- tests/test_utility.py
#3 
Add Sensor class, which allows for there to be relative field sampling.
Simply call a Sensor object with a position, an angle and a rotation axis.
The field of one or more sources may be extracted from its relative position by calling the Sensor's getB.
<details>
<summary>Click here for Example and details</summary>
```py
from magpylib import source, Sensor, Collection
the_position = [0,0,0]
angle = 90
axis = (0,0,1)
sensor = Sensor(the_position,angle,axis)
cyl = source.magnet.Cylinder([1,2,300],[0.2,1.5])
relativeReading = sensor.getB(cyl)
print(relativeReading)
absoluteReading = cyl.getB(the_position)
print(absoluteReading)
box = source.magnet.Box([1,2,300],[1,1,0.5])
col = Collection(cyl,box)
relativeReading = sensor.getB(col)
print(relativeReading)
absoluteReading = …
```
> [WIP] Sensor class feature

- magpylib/_lib/classes/currents.py
- magpylib/_lib/classes/magnets.py
- magpylib/_lib/classes/moments.py
- tests/test_fields/test_CurrentLine.py
- tests/test_sources/test_currents/test_Circular.py
- tests/test_sources/test_currents/test_Line.py
- tests/test_sources/test_magnets/test_Box.py
- tests/test_sources/test_magnets/test_Cylinder.py
- tests/test_sources/test_magnets/test_Sphere.py
- tests/test_sources/test_moments/test_Dipole.py
#188 
Improved classes moments, magnets and currents, implemented __repr__ classes
> Class improvements

- CHANGELOG.md
- docs/conf.py
- setup.py
#196 
This updates the changelog and bumps the Docs and Configuration version to 1.2.0.
> Bump version number to 1.2.0

- magpylib/_lib/classes/collection.py
- magpylib/_lib/classes/magnets.py
- magpylib/_lib/classes/sensor.py
- magpylib/_lib/fields/PM_Facet.py
- magpylib/_lib/utility.py
- magpylib/source/__init__.py
- magpylib/source/magnet/__init__.py
- tests/test_sources/test_magnets/test_Facet.py
#14 
Include the scaffolding for the Facet Class.
- Importable Source entry
- Some Input checking 
- displaySystem entry
- Docstrings
<details>
<summary> Click here for code </summary>
```python
#!/usr/bin/env python3
"""
Created on Mon Jul 29 15:21:59 2019
@author: jim
"""
from magpylib import source, Collection
from numpy import array 
from magpylib import math
magnetization = [2,2,2]
col = Collection()
axesToRotate = [[0,0,1],
[0,1,0],
[1,0,0]]
tilt = 8
baseVertices = array([ array([tilt,0,0]),
array([0,tilt,0]),
array([0,0,tilt]) ] )
col.addSources(source.magnet.Facet(magnetization,baseVertices))
col.addSources(source.magnet.Facet(magnetization,-baseVertices))
for axis in axesToRotate:
vertices = math.rotatePosition(baseVertices,90,axis,anchor=[0,0,0]) …
```
> Facet Class

- CHANGELOG.md
- docs/_pages/0_documentation.rst
- docs/_pages/1_how2install.rst
- docs/conf.py
- docs/index.rst
- magpylib/_lib/classes/currents.py
- magpylib/_lib/classes/magnets.py
- magpylib/_lib/classes/moments.py
- magpylib/_lib/fields/Current_CircularLoop.py
- magpylib/_lib/fields/Current_CircularLoop_vector.py
- magpylib/_lib/fields/Current_Line_vector.py
- magpylib/_lib/fields/Moment_Dipole_vector.py
- magpylib/_lib/fields/PM_Cylinder.py
- magpylib/_lib/fields/PM_Cylinder_vector.py
- magpylib/_lib/getBvector.py
- magpylib/_lib/mathLib_vector.py
- setup.py
- tests/test_Collection.py
- tests/test_MathVector.py
- tests/test_fields/test_CurrentLine.py
- tests/test_magpyVector.py
- tests/test_sources/test_getB_vectorInput.py
This completes the vectorized code which bumps us to version 2.3.0 - ready for publication !!! 🥇
> Vector Code Completion

- docs/_pages/0_documentation.rst
- docs/_pages/4_contguide.rst
- docs/index.rst
- docs/pyplots/examples/01_SimpleCollection.py
> small doku fix

- magpylib/_lib/display/disp_utility.py
- magpylib/_lib/display/display.py
- magpylib/_lib/display/mpl_draw.py
- magpylib/_lib/fields/field_wrap_BH_level2.py
- magpylib/_lib/utility.py
- tests/test_display.py
- tests/test_exceptions.py
- tests/test_getBH_level2.py
#298 should be solved now - short paths are treated as static
#287 completed with graphic integrstion
Level2 layout also massively improved
> Magpylib3 development

- magpylib/__init__.py
- magpylib/_lib/obj_classes/__init__.py
- magpylib/_lib/obj_classes/class_BaseGeo.py
- magpylib/_lib/obj_classes/class_Collection.py
- magpylib/_lib/utility.py
- tests/test_display.py
- tests/test_exceptions.py
- tests/test_getBH_interfaces.py
- tests/test_getBH_level2.py
- tests/test_getBHv.py
- tests/test_obj_BaseGeo.py
- tests/test_obj_Box.py
- tests/test_obj_Circular.py
- tests/test_obj_Collection.py
- tests/test_obj_Cylinder.py
- tests/test_obj_Sensor.py
- tests/test_obj_Sphere.py
- tests/test_path.py
- tests/test_utility.py
- tests/test_vs_mag2.py
Complete rework of the path functionality. It much more natural now ! no more steps ! Thanks to Benjamin K. for pointing this functionality out.
#303
The context manager for path merging is now obsolete
#270
> complete path rework

- magpylib/_lib/input_checks.py
- magpylib/_lib/obj_classes/class_BaseGeo.py
- magpylib/_lib/obj_classes/class_Collection.py
- tests/test_input_checks.py
- Setting up an input check structure
- Introduce Base geo input checks
- improve Base Geo code layout
> input checks base geo

- magpylib/_lib/fields/field_wrap_BH_level2.py
- magpylib/_lib/input_checks.py
- magpylib/_lib/obj_classes/class_BaseExcitations.py
- magpylib/_lib/obj_classes/class_BaseGeo.py
- magpylib/_lib/obj_classes/class_BaseGetBH.py
- magpylib/_lib/obj_classes/class_BaseHomMag.py
- magpylib/_lib/obj_classes/class_Sensor.py
- magpylib/_lib/obj_classes/class_current_Circular.py
- magpylib/_lib/obj_classes/class_mag_Box.py
- magpylib/_lib/obj_classes/class_mag_Cylinder.py
- magpylib/_lib/obj_classes/class_mag_Sphere.py
- magpylib/_lib/obj_classes/class_misc_Dipole.py
- magpylib/_lib/utility.py
- tests/test_input_checks.py
- tests/test_utility.py
#309
- complete input checks
- improve code layout
- introduce BaseExcitation classes
> Mag3 base class homo mag

- docs/_pages/9_physics.rst
- docs/index.rst
> iteration3

- docs/_pages/9_physics.rst
> final iteration

- magpylib/_lib/utility.py
- tests/test_obj_Collection.py
> First bugfix

- Makefile
> Add deployment makefile

- Makefile
#260 
Readds the missing makefile for CD in CIrcleCI
> Add deployment makefile (#341)

- MANIFEST.in
- docs/conf.py
- setup.py
> Update release version and license year

- MANIFEST.in
- docs/conf.py
- setup.py
* Update release version and license year
* Create MANIFEST.in
Latest manifest file for pypi
* Add hotfix for pypi version
> Update release version and license year (#343)

- magpylib/_src/default_classes.py
- magpylib/_src/default_utils.py
- magpylib/_src/defaults.py
- magpylib/_src/display/disp_utility.py
- magpylib/_src/display/display.py
- magpylib/_src/display/mpl_draw.py
- magpylib/_src/display/plotly_draw.py
- magpylib/_src/style.py
- tests/test_defaults.py
- tests/test_display_matplotlib.py
- tests/test_display_plotly.py
> Improve extra user 3d model

- magpylib/_src/fields/field_BH_loop.py
- magpylib/_src/input_checks.py
- magpylib/_src/obj_classes/class_BaseGetBH.py
- magpylib/_src/obj_classes/class_Collection.py
- magpylib/_src/utility.py
- tests/test_obj_Collection.py
- tests/test_utility.py
#410 
Implements Mixed Collections and the ability to mix Sensor and Source Collections
> Implement Mixed collections

- magpylib/_src/fields/field_wrap_BH_level2.py
- tests/test_getBH_level2.py
> squeeze, sumup bugfix and test

- magpylib/_src/display/disp_utility.py
- tests/test_display_utility.py
fixes #429 
The bug was appearing when a vertex is exactly in minus `y` direction
> Line direction bug

- magpylib/_src/obj_classes/class_BaseRotation.py
- setup.py
- tests/test_obj_BaseGeo.py
> scipy 1.7 and rotvec fix

- magpylib/_src/display/display.py
- magpylib/_src/display/mpl_draw.py
fixes #441 
Just a `-` instead of `+` bug fix.
Also fixes a regression introduced by #435 were the `path` argument of the `display` function was conflicting with the `style.path.show` property (only for the `matplotlib` backend
> Fixing scene range calculation

- magpylib/_src/obj_classes/class_BaseGeo.py
- tests/test_obj_BaseGeo.py
> Avoid copy overhead

- CHANGELOG.md
- magpylib/__init__.py
- setup.py
bump version to 4.0.0rc1 for a new pre-release
> bump version 4.0.0rc1

- magpylib/_src/obj_classes/class_BaseGeo.py
- tests/test_obj_BaseGeo.py
> Fix copy order bug

- .pylintrc
- CHANGELOG.md
- magpylib/__init__.py
- magpylib/_src/style.py
- magpylib/_src/utility.py
- setup.py
changes:
* Exclude redundant properties with `_all` suffix in the `.describe()` method ([#534](https://github.com/magpylib/magpylib/pull/534))
* Docstring improvements ([#535](https://github.com/magpylib/magpylib/pull/535))
> 🚀 4.0.4 release

- magpylib/_src/fields/field_BH_facet.py
- magpylib/_src/fields/field_BH_tetrahedron.py
- magpylib/core/__init__.py
facets and Tetrahedra solution
> Facet and tetraeder

- CHANGELOG.md
- magpylib/__init__.py
- setup.py
> 🚀 4.1.0 release

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- docs/examples/examples_31_end_of_shaft.md
- magpylib/_src/fields/field_BH_loop.py
- magpylib/_src/fields/special_cel.py
> Misc fixes

- CHANGELOG.md
- magpylib/__init__.py
- setup.py
Quick fix release, to avoid waiting for 4.2 release with facets.
> 🚀 4.1.2 release

- CHANGELOG.md
- README.md
- azure-pipelines.yml
- docs/_pages/page_03_installation.md
- setup.py
> Drop python 3.7 support

- CONTRIBUTING.md
> Doku rework peter

- magpylib/_src/display/backend_plotly.py
- magpylib/_src/display/traces_generic.py
- magpylib/_src/display/traces_utility.py
Fixes small bugs related to the use of extra traces for external use cases.
> Plotly extra traces fix

- magpylib/_src/display/traces_generic.py
- fixes #649
magnetization criteria fixed (bad parenthesis)
> Fix Matplotlib magnetization colors display for valid magnetization

- CONTRIBUTING.md
- docs/README.md
- docs/_pages/docu/docu_graphics.md
- docs/_pages/gallery/gallery_tutorial_collection.md
- docs/_pages/gallery/gallery_tutorial_field_computation.md
- docs/_pages/gallery/gallery_tutorial_paths.md
- docs/_pages/reso_news.md
- docs/index.md
> Fix small typos in docs

- CHANGELOG.md
- README.md
- docs/_pages/gallery/gallery_app_halbach.md
- docs/_pages/gallery/gallery_app_helmholtz.md
- docs/_pages/gallery/gallery_misc_compound.md
- docs/_pages/gallery/gallery_shapes_pyvista.md
- docs/_pages/gallery/gallery_tutorial_field_computation.md
- docs/_pages/gallery/gallery_vis_mpl_streamplot.md
- docs/_pages/reso_news.md
- magpylib/__init__.py
- setup.py
Including 28 issues included in [Milestone 4.4](https://github.com/magpylib/magpylib/milestone/7)
> 🚀 4.4.0 release

- docs/_pages/gallery/gallery_shapes_convex_hull.md
- docs/_pages/gallery/gallery_shapes_superpos.md
- docs/_pages/gallery/gallery_shapes_triangle.md
- docs/_pages/gallery/gallery_vis_mpl_streamplot.md
- docs/_pages/gallery/gallery_vis_pv_streamlines.md
- docs/_pages/reso_news.md
Some minor docu improvements and bug fixes for the gallery
- #659
> Doku fix gallery

- CHANGELOG.md
- README.md
- magpylib/__init__.py
- magpylib/_src/input_checks.py
- setup.py
> 🚀 4.4.1 release

- docs/conf.py
> Add announcement banner to the docs to warn for upcoming v5 breaking changes

- .github/workflows/codeql.yml
- .github/workflows/python-app.yml
- docs/_pages/gallery/gallery_app_end_of_shaft.md
There is no need to trigger unit-testing when only the docs are modifed. We already have the docs build triggered on pull requests and this hast to pass in order to merge.
> Do not trigger unit tests on docs-only changes

- docs/_pages/docu/docu_magpylib_api.md
- docs/_pages/gallery/gallery_app_helmholtz.md
> fix units in coil example

- magpylib/_src/fields/field_wrap_BH.py
- magpylib/_src/obj_classes/class_Collection.py
- tests/test_getBH_interfaces.py
- tests/test_obj_Collection.py
> Fix Collection getB - Bug

- docs/_pages/docu/docu_physics.md
- magpylib/_src/fields/field_BH_cuboid.py
> Fix issue 761

- .github/workflows/python-app.yml
- README.md
- docs/_pages/reso_get_started.md
- pyproject.toml
- tox.ini
- #772
Proposal to follow the minimum scientific packages versions as defined in :
https://scientific-python.org/specs/spec-0000/
> follow scientific-python.org support timelines

- docs/_static/switcher.json
Fixes docs version-switcher versions to be shown.
> Fix docs vesion-switcher

- magpylib/_src/display/traces_generic.py
- tests/test_display_plotly.py
> Fix markers legend not being suppressible

- CHANGELOG.md
- magpylib/_src/fields/field_BH_circle.py
- magpylib/_src/fields/field_BH_cylinder.py
- magpylib/_src/fields/field_BH_dipole.py
- tests/test_field_cylinder.py
- #792
@OrtnerMichael I would suggest to make a release right away !
> Add support for Numpy 2.0

- CHANGELOG.md
- README.md
- docs/_pages/user_guide/docs/docs_fieldcomp.md
- docs/_pages/user_guide/docs/docs_pos_ori.md
- docs/_pages/user_guide/examples/examples_misc_inhom.md
- docs/index.md
- #794 
change naming in documentation from explicit to analytical
> Explicit to analytical

- magpylib/_src/display/backend_pyvista.py
This will enable merging:
- #804 
- #806
- #807
> Fixed pyvista scalar bar removal routine 

- CHANGELOG.md
- magpylib/_src/display/traces_generic.py
> Fixed magnetization arrow positioning when barycenter differs from position

- CHANGELOG.md
- README.md
- docs/_static/switcher.json
- magpylib/__init__.py
- #805 
- #786 
- #794 
- #798 
- #799 
- #802 
- #766 
- #787
> 🚀 5.1.0 release 

- magpylib/_src/fields/special_cel.py
Remove unneccesary copy in celv function since kk is already copied from k in lines above.
> Optimize celv function in special_cel.py

- CHANGELOG.md
- docs/_pages/user_guide/examples/examples_misc_equivalent.md
- src/magpylib/_src/display/traces_utility.py
- tests/test_display_plotly.py
- Fixes #872
@OrtnerMichael Can you please quickly check this, I would then follow with a 5.2.1 release. Thanks
> Fix source duplication in field calculation when using dynamic 2d subplots with field output
