magpylib/magpylib

- MANIFEST.in
- setup.py
PyPi was not bundling the LICENSE in the latest release, this MANIFEST.in should fix it.
> Bundle LICENSE with PyPi package

- magpylib/_lib/classes/fieldsampler.py
- tests/test_base/test_fieldsampler.py
#151 
This change will force getBsweep to return a numpy array with all the results from getBsweep operations.
It seems backwards compatible enough to be a patch, but could still break crazy scripts which try to use list methods over the result if there are any out there yet.
> Force getBsweep to return array

- magpylib/_lib/fields/Current_Line.py
- tests/test_fields/test_CurrentLine.py
#162 
This has the field calculation return `[0,0,0]` for repeated segments, it will also throw a warning.
> Fix zero length

- magpylib/_lib/classes/collection.py
#174 
This adds the `block=False` kwarg to `plt.show()` in Collection.displaySystem(), allowing displaySystem to work as intended in environments where interactive mode is off.
If for some reason users want to have displaySystem() block execution, users may use `suppress=True` and call upon `plt.show()`externally without the keyword.
> Add block kwarg to displaySystem's plt.show()

- magpylib/_lib/classes/collection.py
- magpylib/_lib/utility.py
@lucasgcb 
please check out these changes.
I notices that there were some functions in utility that are used in displaySystem to draw quivers. However, they were given 'pyplot' as argument rather than the respective axis. In this case matplotlib always gives plt.gca() (which is the current active axis).
With the new option subplotAx in displaySystem it is now possible to activate other axes BEFORE the plotting takes place. so the quiver objects will jump to the last used axis.
This problem should be fixed with this commit, but please double check it!!!
> display system fix (ax reference instead of plt)

- magpylib/_lib/classes/collection.py
- tests/test_Collection.py
#164 
This adds handling for when `Collection.getBsweep(multiprocessing=True)` happens to have several objects but too few positions to parallelize efficiently, which ends up costing performance.
Benchmark Code:
https://gist.github.com/lucasgcb/40f5979d9436a671ed2600e429f52fa2
Benchmark was run with getBsweep of 1 Object for 10000 positions and getBsweep of compounding 10000 objects in 1 position.
<details>
<summary> Click Here for Benchmark Results </summary>
As we expected, running getBsweep when there are too few positions resulted in ridiculous processing times. I had to cancel out at 500 Objects since time was getting worse by each step.
After the tweak, getBsweep achieved a more acceptable processing time for 10000 objects.
Note how doing this is a more complex operation than …
> Enhance collection getBsweep

- docs/_pages/1_how2install.md
- docs/_pages/2_guideExamples.md
- docs/_pages/3_MATLAB.md
- docs/pyplots/examples/01b_AllSources.py
- docs/pyplots/examples/03a_Bsweep1.py
- docs/pyplots/examples/04_ComplexShape.py
- docs/pyplots/examples/05_Multiprocessing.py
- Some typos 
- Anchor links from the TOC in Installation page being weird.
- Example code being "Inline mode unfriendly". Examples should now work in whatever graphics backend the user has currently
- References of "Matlab" instead of "MATLAB" in the MATLAB page.
- Spyder's Warning -  this is actually a problem with IPython (which is run inside Spyder) and it will show up on other IDEs that utilize it. I've attempted to clarify this so users can take appropriate measures.
> Proofread dokuv2

- magpylib/_lib/classes/base.py
- tests/test_base/test_base.py
This adds axis input protection to all RCS enabled objects.
An assertion will check if the axis input follows the following format:
`(numeric,numeric,numeric)`
where `numeric` is any rational number different from 0.
> Add axis input typechecking to all RCS objects

- magpylib/_lib/classes/currents.py
- magpylib/_lib/classes/magnets.py
- magpylib/_lib/classes/moments.py
- magpylib/_lib/utility.py
- tests/test_utility.py
None
This places the utility functions for getB of all source objects inline, saving on function calls.
The downside is that it looks not as nice.
Also, deprecate utility functions for getB and their tests.
> Inline utility functions for getB

- docs/_pages/0_documentation.md
- docs/pyplots/doku/sensorSource.py
- docs/pyplots/doku/thorsHammerSensor.py
#3 
This adds an entry for the Source class in the Library documentation section.
Take a look here:
https://magpylib.readthedocs.io/en/guide-sensor/_pages/0_documentation/#the-sensor-class
> Add sensor entry in docs

- .circleci/config.yml
- CHANGELOG.md
- azure-pipelines.yml
#266 
#258
- Renamed test step in Circle CI to specify it delivers coverage data to our [codecov](https://app.codecov.io/gh/magpylib/magpylib) page
- Added Azure Pipelines trigger to magpylib3_development and to branches starting with `feature-`
- Dropped Python 3.6 from Azure Pipelines testing configuration
- Added Python 3.8 and 3.9 to Azure Pipelines testing configuration
- Readded CHANGELOG.md with previous changelog data
- Added missing version comparisons links to CHANGELOG.md
> Magpy3 Azure Testing Suite

- magpylib/_lib/display/disp_utility.py
When using the `display()` function, a Cylinder source is displayed in 3D plot with dimensions that differ from the ones defined. Given the sample below, a cylinder with a diameter of 10 mm and a height of 4mm is displayed as  a cylinder of diameter equals to 10 mm and a height of 20 mm.
```python
from magpylib.magnet import Cylinder
from magpylib._lib.display.disp_utility import faces_cylinder
src1 = Cylinder(mag=[0, 0, 1000], dim=[10, 4])
magpy.display(src1, show_path=False)
faces = faces_cylinder(src1, False)
```
This comes from the `faces_cylinder()` function, where the z component of each vertex of a face is multiplied by the radius `r`, instead of just x and y components.
Furthermore, the double iteration over the `hs` iterable (`-h2, +h2`) causes the …
> fix wrong Cylinder faces

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question_magnetics.md
- .github/PULL_REQUEST_TEMPLATE.md
#304 
Simply adds the [github configuration](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates) files we had in the default before back into the new version, for when it reaches master.
> Readd GitHub community cfg file

- docs/index.rst
- docs/requirements.txt
- magpylib/__init__.py
#292 
- The index.rst file had been modified by an earlier commit which caused Sphinx to not import the library docstrings into the side bar; This patch fixes this.
- Fixed some grammar on the page and the ``__init__.py`` bullet list.
- Lock Sphinx to 1.8.2 in the requirements because our configuration is exclusive for that version (currently Sphinx is on 4.0).
> Fix Docstring Menu

- README.md
#337 
#284 
This should fix the aspect ratio of the images on mobile devices. The informative graphic might be harder to read on such displays.
Also, remove the app veyor badge, and add the download counter badge from conda cloud.
https://github.com/magpylib/magpylib/tree/fix-readme
> Update badges, Fix images on Readme

- magpylib/_src/obj_classes/class_BaseDisplayRepr.py
- magpylib/_src/obj_classes/class_Collection.py
- tests/test_obj_Cuboid.py
Adds a name entry, if available, in object representations. This feature is meant to ease the tracking of objects  when runing a script or when debugging
```python
pm1 = magpy.magnet.Cuboid((1,2,3),(1,2,3))
pm2 = magpy.magnet.Cuboid((1,2,3),(1,2,3))
pm2.style.name = 'cuboid_01'
print(pm1)
print(pm2)
```
output:
```
Cuboid(id=140470723768480)
Cuboid(id=140470723768960, name='cuboid_01')
```
> Name in repr

- magpylib/_src/obj_classes/class_BaseDisplayRepr.py
- magpylib/_src/obj_classes/class_BaseExcitations.py
- magpylib/_src/obj_classes/class_BaseGeo.py
- magpylib/_src/obj_classes/class_BaseGetBH.py
- magpylib/_src/obj_classes/class_Sensor.py
- magpylib/_src/obj_classes/class_current_Line.py
- magpylib/_src/obj_classes/class_current_Loop.py
- magpylib/_src/obj_classes/class_mag_Cuboid.py
- magpylib/_src/obj_classes/class_mag_Cylinder.py
- magpylib/_src/obj_classes/class_mag_CylinderSegment.py
- magpylib/_src/obj_classes/class_mag_Sphere.py
- magpylib/_src/obj_classes/class_misc_Custom.py
- magpylib/_src/obj_classes/class_misc_Dipole.py
- tests/test_obj_BaseGeo.py
This PR allows the style properties to be set via underscore magic also at initialization. So far it was only possible explicitly via a dictionary.
```python
pm = magpy.magnet.Cuboid((
1,2,3),(1,2,3), 
style=dict(name='name_01')
)
print(pm.style.name)
```
```python
pm = magpy.magnet.Cuboid((
1,2,3),(1,2,3), 
style_name='name_01')
)
print(pm.style.name)
```
```python
pm = magpy.magnet.Cuboid((
1,2,3),(1,2,3), 
stylee_name='name_01')
)
print(pm.style.name)
```
`style magic` updates `style dict` as shown below
```python
pm = magpy.magnet.Cuboid((
1,2,3),(1,2,3), 
style=dict(name='name_01'), 
style_name='name_02'
)
print(pm.style.name)
```
> Style magic in object init

- magpylib/_src/display/disp_utility.py
- magpylib/_src/display/mpl_draw.py
- magpylib/_src/style.py
- tests/test_display_matplotlib.py
Some matplotlib functions such as `plot_trisurf` only allow coordinates to be provided via positional arguments. When providing an extra model3d, one needs a way to provide such arguments via a dictionary while allowing the magpylib library take care of the positioning and orienting of the provied trace.
This is useful if we want to provide a complex model originating from a CAD model and plot it with the magpylib display function. For example a complex mesh object representing a 3d-model of  sensor can be attached to a magpylib sensor and moved automatically with it. 
```python
import os
import tempfile
import numpy as np
import plotly.graph_objects as go
import requests
from stl import mesh  # needs numpy-stl installed
def get_stl_color(x, …
```
> improve extra model3d to accommodate positional arguments in plotting function

- magpylib/_src/display/display.py
- magpylib/_src/display/mpl_draw.py
When calculating the system range, magnetization arrows are not accounted for.  In this PR arrow tips are included in the range calculation.
The only question which remains is: **do we want this behavior ?**
```python
s1 = magpy.magnet.Cuboid((0,0,1), (1,1,1), (0,1,0), style_magnetization_size=1.5)
s2 = magpy.magnet.Cuboid((1,0,0), (1,1,1), (0,0,0), style_magnetization_size=1.5)
magpy.display(s1, s2, zoom=0)
```
> Include magnetization arrows in display range calculation

- magpylib/_src/default_utils.py
- magpylib/_src/defaults.py
- magpylib/_src/display/display.py
- magpylib/_src/display/plotly_draw.py
- magpylib/_src/style.py
- tests/test_defaults.py
> Path style improvements

- docs/examples/plot_02_display_backends.md
- docs/examples/plot_03_display_styling.md
- docs/examples/plot_07_custom_source.md
- docs/examples/plot_08_complex_extra_model3d.md
- magpylib/_src/defaults/defaults_utility.py
- magpylib/_src/defaults/defaults_values.py
- magpylib/_src/display/__init__.py
- magpylib/_src/display/display_matplotlib.py
- magpylib/_src/display/display_utility.py
- magpylib/_src/display/plotly/plotly_display.py
- magpylib/_src/display/plotly/plotly_utility.py
- magpylib/_src/style.py
- magpylib/display/style/__init__.py
- tests/test_Coumpound_setters.py
- tests/test_defaults.py
- tests/test_display_matplotlib.py
- tests/test_display_plotly.py
- tests/test_missing_plotly.py
This PR aims to slightly rework the extra `model3d` syntax.
- `style.model3d.extra` is now `style.model3d.data`
- `style.model3d` has a new `add_trace` method which allows easy building of extra traces.
- 'style.model3d.show` is replaced by `style.model3d.showdefault` which hides only the default trace
- library docstrings for `Magnet`, `Current`, `Dipole` and `Sensor` styles have been updated and added to the top level library and the docs under `magpylib.display.style`
> Style model3d rework

- magpylib/_src/obj_classes/class_BaseGeo.py
- magpylib/_src/obj_classes/class_Collection.py
- magpylib/_src/utility.py
- tests/test_obj_BaseGeo.py
- tests/test_obj_Collection.py
- tests/test_utility.py
This PR adds the `copy` method to the `BaseGeo` class. The method can also take keyword arguments as input, which are transmitted to the new object. 
The `copy` method for the `Collection` was only returning a shallow copy. Since we have changed its philosophy, the `Collection` inherits from `BaseGeo` and also its new `copy` method which now returns a deep copy of the object.
```python
col = magpy.Collection(
magpy.magnet.Cuboid(magnetization=(1,0,1), dimension=(8, 4 ,6), position=(0,0,0)),
magpy.magnet.Cylinder(magnetization=(0,1,0), dimension=(8, 5), position=(-15,0,0)),
style_name='Collection_01'
)
col2 = col.copy(position=(0,0,10), style=dict(color='red'), style_color='orange')
magpy.show(col, col2, style_magnetization_show=False, backend='plotly')
```
> Basegeo copy method

- docs/examples/plot_07_custom_source.md
- magpylib/_src/display/display_matplotlib.py
- magpylib/_src/display/plotly/plotly_display.py
- magpylib/_src/obj_classes/class_BaseDisplayRepr.py
- magpylib/_src/obj_classes/class_BaseGeo.py
- magpylib/_src/style.py
- tests/test_Coumpound_setters.py
- tests/test_obj_BaseGeo.py
- tests/test_obj_Cuboid.py
#397
if we want to implement #397, the `name` attribute is already reserved in the `param` library. So we change it beforehand to `label` to avoid api change in the future because of this incompatibility. Anyway we also agreed with @OrtnerMichael, that the term `label` makes more sense.
> `style.name` ➡️  `style.label`

- magpylib/_src/display/display_matplotlib.py
- magpylib/_src/display/display_utility.py
- magpylib/_src/display/plotly/plotly_display.py
This PR addresses a small display weirdness of CylinderSegment magnetization arrow . When the segment angle (phi1 - phi2) is large the arrow starts at a off-center position. With this PR, off-center arrow start is now using the new barycenter property of the Cylinder Segment. 
**EDIT: do not merge before checking #484**
```python
import numpy as np
sources = []
for k,sign in enumerate([-1,1]):
for j,mag in enumerate([(1,0,0),(0,1,0),(0,0,1)]):
for i, phi in enumerate((90,180,270, 350)):
src = magpy.magnet.CylinderSegment(
magnetization=np.array(mag)*sign, 
dimension=(1,2,1,0,phi),
position=(-6*i,7*j,15*k))
sources.append(src)
magpy.show(sources, style_opacity=0.1)
```
@OrtnerMichael please have a look ;)
> Improve CylinderSegment magnetization matplotlib display

- magpylib/_src/display/plotly/plotly_sensor_mesh.py
When they have no pixels, multiple sensors cannot be simply distinguished from each other. This PR solves this issue by colorizing the tail of the coordinate arrows separately.
This fix is plotly only and does not include a matplotlib equivalent (yet @OrtnerMichael ?). 
Should this be a specific style option to turn on/off (`style.arrow.colorizetails` ) ?
```python
import numpy as np
t = np.linspace(-0.1,0.1,5)
pixel  = [[x,y,z] for x in t for y in t for z in t]
s0 = magpy.Sensor(position=(2,0,0), style_label='Sensor1', style_size=4)
s0.style.pixel.size = 0.5
sensors = [s0.copy(position=(i,j,-2*k), pixel=p) for i in range(2) for j in range(2) for k,p in enumerate(((0,0,0), pixel))]
magpy.show(sensors, backend='plotly', renderer='browser')
```
> colorize sensor coordinate arrow tails

- azure-pipelines.yml
- magpylib/_src/__init__.py
- magpylib/_src/fields/field_wrap_BH_level2.py
- magpylib/_src/input_checks.py
- magpylib/_src/obj_classes/class_Sensor.py
- magpylib/_src/utility.py
- tests/test_exceptions.py
- tests/test_getBH_level2.py
- tests/test_input_checks.py
- tests/test_obj_Sensor.py
**notes**
The origin of the original problem was that the input `[(1,2,3)]` was interpreted as a list with one position vector `(1,2,3)`, rather than just one bare position vector `((1,2,3),)`.
**changes**
- improved/added `test_format_input_observers`
- moved `test_format_input_observers` from utility to input checks
- fixed tests
- added tests
- pylint
- coverage
- simplification of check_format_input_vector
- minor improvements
**getB(squeeze=False) behavior**
1. `getB(squeeze=False)` minimal shape is (1,1,1,1,3)      *<reshape bare input pixel as (1,3) in getBH>*
2. `Sensor(pixel=pos_vec).pixel == np.array(pos_vec)`     *<no squeezing around of sensor pixel input>*
3. Complete equivalence between `getB(pos_vec)` and `getB(Sensor(pixel=pos_vec))` *<new logical equivalent>*
> Fix pixe squeeze

- docs/examples/examples_03_collections.md
- magpylib/_src/obj_classes/class_Collection.py
- tests/test_obj_Collection.py
- tests/test_obj_Collection_child_parent.py
This adds `children_all`, `sources_all`, `sensors_all` and `collections_all` as collection parameters that return all respective objects in the tree. Returns some of the previous collection behavior.
```python
s1 = magpy.Sensor(style_label='s1')
s2 = s1.copy()
s3 = s2.copy()
coll = s1 + s2 + s3
coll.describe(format='label')
```
Collection    
├── Collection
│   ├── s1    
│   └── s2    
└── s3        
```
print([s.style.label for s in coll.sensors])
```
['s3']
```
print([s.style.label for s in coll.sensors_all])
```
['s1', 's2', 's3']
```
> adding _all parameters

- magpylib/_src/obj_classes/class_Collection.py
- tests/test_obj_Collection_child_parent.py
#459
A Collection should not be able to reference itself, otherwise it'd break every recursion algorithm acting on collections such as `getB`/`getH` `show` among others. This PR catches at the collection `add` method.
> Catch `Collection` self referencing

- .binder/apt.txt
- .binder/start
- .readthedocs.yaml
- docs/conf.py
- docs/examples/examples_30_coil_field_lines.md
Fixes docs failing to build when Pyvista output are required.
Also allows mybinder.org to be able to render Pyvista outputs.
useful links:
https://github.com/pyvista/pyvista/issues/313
https://docs.pyvista.org/getting-started/installation.html
> Pyvista dependencies

- magpylib/_src/display/plotly/plotly_display.py
When plotting a large number of objects (>500). The plotly plottting backend starts to struggle rendering all the objects. When displaying a large collection of similar objects within a collection it is possible to group and merge the similar traces into a much smaller number of traces. This drastically improves browser rendering performance. In this PR, a method is implemented to group and merge traces based on criteria such as `("legendgroup", "line", "marker", "colorscale", ...)`.
Of Course, this only applies if the object are displayed within a Collection and are not unpacked in the `show` function, since otherwise every object gets it's own legend entry and therefore its own trace, which would prevent merging.
More performance increase could be achieved on the construction of the …
> Plotly plotting performance

- magpylib/_src/display/plotly/plotly_utility.py
The magnetization coloring was failing when magnets are grouped into a collection and have quite different sizes and magnetization. The intensity calculation for the magnetization color scale was not normalized and when merging traces was leading to a bad magnetization representation with plotly. 
This PR fixes this regression introduced by #524. 
```python
from magpylib.magnet import Cuboid, Cylinder, Sphere
import plotly.graph_objects as go
cube = Cuboid(magnetization=(0, 0, 1), dimension=(1, 2, 2))
cylinder = Cylinder(magnetization=(0, 100000, 0), dimension=(1, 1), position=(2,0,0))
sphere = Sphere(magnetization=(0, 1, 1), diameter=1, position=(4,0,0))
coll = magpy.Collection(cube, cylinder, sphere)
magpy.show(coll, backend="plotly")
```
> Fix magnetization coloring with mesh grouping (plotly)

- magpylib/_src/defaults/defaults_utility.py
- tests/test_default_utils.py
#527
**Merge this into 4.0.2 branch before 4.0.2 release !**
To consider: Opaqueness is automatically set to 1 when providing a float color. The alpha entry is ignored.
We can now do this:
```
from matplotlib import pyplot as plt
cmap = plt.cm.get_cmap('jet')
coll = magpy.Collection()
for i in range(10):
cube = magpy.magnet.Cuboid(
magnetization=(0,0,1000),
dimension=(1,1,1),
position=(i,0,0),
)
cube.style.color=cmap(i/10)
coll.add(cube)
magpy.show(*coll)
```
> allowing float colors, adding tests, pylint

- CHANGELOG.md
- magpylib/__init__.py
- setup.py
> 🚀 4.1.1 release

- .pylintrc
- docs/examples/examples_12_styles.md
- magpylib/_src/display/backend_matplotlib.py
- magpylib/_src/display/backend_plotly.py
- magpylib/_src/display/traces_base.py
- magpylib/_src/display/traces_generic.py
- magpylib/_src/display/traces_utility.py
- magpylib/_src/obj_classes/class_Collection.py
- magpylib/_src/style.py
- Fixes an  graphics style example of the documentation
- Also update code base for pylint>=2.16
@OrtnerMichael 
Not sure if it is worth doing an release fix yet. I think it can wait for the 4.3 release. Anyway I'm working on more flexible and robust style defaults
> Graphics-style docs fix

- docs/examples/examples_31_end_of_shaft.md
- docs/index.md
> General docu improvements

- magpylib/_src/obj_classes/class_BaseGeo.py
When working on some routine code where the creation of magpylib objects is very frequent, specifying style attributes cost some significant additional initialization time, so we tend to avoid using them in these cases. However it is quite convenient to be able to give at least a `style.label` to our objects in order to track them more easily later.
This PR partly addresses this issue by deferring the style class tree initialization to when it is really called explicitly (e.g. `obj.style`...). It allows to declare some `style_kwargs` at init level without carrying the time penalty right away. This would be even more relevant if we decide to implement #397.
Here some before/after examples to illustrate the use cases:
> Defer Style initialization to when it is needed

- azure-pipelines.yml
python 3.11 has been out 4 month now. Time to test magpylib against it ;)
> test against python 3.11

- docs/examples/examples_03_collections.md
- docs/examples/examples_13_3d_models.md
- magpylib/_src/display/traces_generic.py
- magpylib/_src/display/traces_utility.py
fixes displaying disconnected meshes with plotly. Only discovered in the docs
> fix show disconnected trimesh

- .pre-commit-config.yaml
- CHANGELOG.md
- tests/test_obj_BaseGeo.py
update hooks:
- reorder-python-imports
- pyupgrade
@OrtnerMichael, don't squash, just merge please
> Update pre-commit hooks for python 3.8+

- CHANGELOG.md
- magpylib/_src/fields/field_BH_line.py
- tests/test_obj_Line.py
- fixes #604
Accepts discontinuous `current.Line` segments by treating them as multiple lines. Only works if all 3 coordinates `x,y,z` are null.
> Accept discontinuous `current.Line` segments and treat as separate lines

- magpylib/_src/display/backend_matplotlib.py
- #661
This PR adds a custom legend handler for matplotlib meshes, "à la plotly".
```python
magpy.show(
*[
magpy.magnet.Cuboid(
magnetization=(0, 0, 1000),
dimension=[0.5] * 3,
position=(x, 0, z),
style_magnetization_color_mode=["tricycle", "tricolor", "bicolor"][z],
style_label=f"Cube {x=}, {z=}",
style_description_show=False,
)
for z in range(3)
for x in range(3)
],
backend="matplotlib",
)
```
> Add custom legend handler for matplotlib meshes

- magpylib/_src/display/sensor_mesh.py
This fixes the mismatch of showed or hidden sensor axes. More specifically the "y" and"z" where switched when trying to hide one.
I would suggest to do a patch fix release right away when this is merged.  I'd have a workaround for a Left Handed Sensor which needs this fix (see #676)
```python
sens = []
for i, k in enumerate("xyz"):
s = magpy.Sensor(
position=(i, 0, 0),
style_label=f"Sensor ({k}-axis hidden)",
style_size=4,
)
s.style.arrows.update({f"{k}_show": False})
sens.append(s)
magpy.show(sens)
```
> Fix axis mismatch on show/hide of sensor arrows

- magpylib/_src/fields/field_BH_cylinder.py
- tests/test_field_cylinder.py
- fixes #703
also added a test for it, relying on the cylinder segment result.
> Fix Cylinder inside H-field computation

- magpylib/_src/display/traces_utility.py
This fixes the wrong labeling of deeply nested collections on `show` call. Label propagation was not working beyond the first level.
```python
cube = magpy.magnet.Cuboid(style_label="cube")
nested = magpy.Collection(cube, style_label="nested")
root = magpy.Collection(nested, style_label="root")
magpy.show(root)
```
> Fix plotting labeling of deeply nested collections

- .github/workflows/python-app.yml
- .readthedocs.yaml
- magpylib/_src/display/traces_core.py
- magpylib/_src/input_checks.py
- magpylib/_src/obj_classes/class_Collection.py
- magpylib/_src/obj_classes/class_current_Circle.py
- magpylib/_src/obj_classes/class_current_Polyline.py
- tests/test_core_physics_consistency.py
- tests/test_defaults.py
- tests/test_getBH_level2.py
- tests/test_obj_BaseGeo.py
This PR addresses some failing tests with the new macos CI backend (similar to numerical stability problems) and some new pylint warnings with new package version. Also sets the minimum version python to 3.10 in github workflows and RTD.
PS: When this is merged, #772  PR will only address the original display fix ;)
> Fix tests with macos CI backend + adapt to pylint and rtd version

- .github/workflows/python-app.yml
The release process was failing because of a wrong version number of python version.
In the publish job, the python version number must be a string and not a number. For versions ending with `0` like `3.10` are interpreted as `3.1` hence the change to `"3.10"`.
@OrtnerMichael I already released the package from this branch, so no need to make a new one once this is merged!
> Fix python version as string in actions/setup-python@v4 for pypi Publishing

- .github/workflows/codeql.yml
- .github/workflows/python-app.yml
Updates to actions/setup-python@v5 and actions/setup-python@v4.
This addresses the following warning:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> Update github actions

- CHANGELOG.md
- magpylib/_src/display/backend_pyvista.py
- #766 
This fixes the plot bounds in pyvista. This was especially visible on animations where the plot ranges were not fixed.
In pyvista there is no known way of setting the bounds manually and setting the camera position by an special algorithm is not practical at all. The solution in this case is to add a transparent scatter plot, that sets the ranges correctly.
This correction also enables the zoom feature which was absent until now!
```python
import numpy as np
cylseg = magpy.magnet.CylinderSegment(
dimension=(3, 4, 1, 0, 45),
polarization=(0, 0, 1),
)
angles = np.linspace(0, 360, 10, endpoint=False)
cylseg.rotate_from_angax(angles, axis="z")
magpy.show(
{"objects": cylseg, "col": 1},
backend="pyvista",
style_legend_show=False,
animation=True, …
```
> Fix pyvista plotting ranges and zoom

- README.md
> Update Readme with stable and latest documentations references

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .readthedocs.yaml
- noxfile.py
- pyproject.toml
Optional dependencies are user facing while dev groups are meant to be for developers.
Additionally, the tool.uv.dev-dependencies option is now a legacy option, per https://docs.astral.sh/uv/concepts/projects/dependencies/#legacy-dev-dependencies
> Move optional-dependencies to dependency groups

- .github/workflows/cd.yml
This fixes the release process
> NOTE
The package is already released from this branch, this merge is just to apply the changes to the main branch
Since the alignment with the Scientific Pyhon Packaging standards the GitHub Action has been changed and the trusted publisher was not working anymore and had to be updated on the pipit account.
Also by default the publishing url was pointing the test instance of PyPI instead of the production one. This was fixed is this PR
> Fix PyPI publishing for package release
